import type { Metadata } from "next";
import localFont from "next/font/local";
import { ReactNode } from "react";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <div className="flex flex-col min-h-screen text-secondary bg-primary">
      <header className="p-4 border-b border-gray-800 text-center">
        <h1 className="text-2xl font-semibold">AI Prompt Generator</h1>
      </header>
      <main className="flex-grow p-4">{children}</main>
      <footer className="p-4 border-t border-gray-800 text-center">
        <p>© 2024 AI Prompt Generator</p>
      </footer>
    </div>
  );
};

export default Layout;
